const config = require('./gulpconf');

const pathConfig = {};

pathConfig.array = [
  {
    // Accordion all collapsed
    label: 'Accordion',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.accordion',
    scrollToSelector: '.accordion',
    delay: 0,
    selectors: ['.accordion'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Accordion all expanded
    label: 'Accordion Expanded',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.accordion',
    scrollToSelector: '.accordion',
    delay: 500,
    clickSelector: '.accordion__expand-all',
    postInteractionWait: 400,
    selectors: ['.accordion'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Generic block: 2 column  w/ images
    label: 'Generic Block: 2 Column w/ image',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.gen2col',
    scrollToSelector: '.gen2col',
    delay: 0,
    selectors: ['.gen2col'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Generic block: 3 column  w/ images
    label: 'Generic Block: 3 Column w/ image',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.gen3col',
    scrollToSelector: '.gen3col',
    delay: 0,
    selectors: ['.gen3col'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Generic block: Image list
    label: 'Generic Block: Image list',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.genimglist',
    scrollToSelector: '.genimglist',
    delay: 100,
    selectors: ['.genimglist'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Program List
    label: 'Program List',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.program-list',
    scrollToSelector: '.program-list',
    delay: 100,
    selectors: ['.program-list'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Statistic 3up Feature
    label: 'Statistic 3up Feature',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.stat3up',
    scrollToSelector: '.stat3up',
    delay: 100,
    selectors: ['.stat3up'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Blog 3up Feature
    label: 'Blog 3up Feature',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.blog3up',
    scrollToSelector: '.blog3up',
    delay: 100,
    selectors: ['.blog3up'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Story Display
    label: 'Story Display',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.story-display',
    scrollToSelector: '.story-display',
    delay: 0,
    selectors: ['.story-display'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Instagram Display
    label: 'Instagram Display',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.instagram__account',
    scrollToSelector: '.instagram__account',
    delay: 0,
    selectors: ['.instagram__account'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Twitter Display
    label: 'Twitter Display',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.twitter__account',
    scrollToSelector: '.twitter__account',
    delay: 0,
    selectors: ['.twitter__account'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // WYSIWYG Display
    label: 'WYSIWYG Display',
    url: `${config.env}/keyscreens/pattern-wysiwyg.html`,
    readySelector: '.wysiwyg',
    scrollToSelector: '.wysiwyg',
    delay: 0,
    selectors: ['.wysiwyg'],
  },
  {
    // Carousel Display
    label: 'Carousel Display',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.carousel',
    scrollToSelector: '.carousel',
    delay: 0,
    selectors: ['.carousel'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Pattern: Objects
    label: 'Pattern: Objects',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Pattern: WYSIWYG
    label: 'Pattern: WYSIWYG',
    url: `${config.env}/keyscreens/pattern-wysiwyg.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Alert: Display
    label: 'Alert: Display',
    url: `${config.env}/keyscreens/alert-display.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // News: Detail
    label: 'News: Detail',
    url: `${config.env}/keyscreens/news-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // News: Listing
    label: 'News: Listing',
    url: `${config.env}/keyscreens/news-listing.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Faculty: Detail
    label: 'Faculty: Detail',
    url: `${config.env}/keyscreens/faculty-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Faculty: List
    label: 'Faculty: List',
    url: `${config.env}/keyscreens/faculty-list.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Program: Detail
    label: 'Program: Detail',
    url: `${config.env}/keyscreens/program-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Blog: Detail
    label: 'Blog: Detail',
    url: `${config.env}/keyscreens/blog-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Calendar: Detail
    label: 'Calendar: Detail',
    url: `${config.env}/keyscreens/calendar-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Calendar: List
    label: 'Calendar: List',
    url: `${config.env}/keyscreens/calendar-list.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Catalog: Course List
    label: 'Catalog: Course List',
    url: `${config.env}/keyscreens/calendar-detail.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Catalog Program: List
    label: 'Catalog Program: List',
    url: `${config.env}/keyscreens/catalog-program-list.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Blog: List
    label: 'Blog: List',
    url: `${config.env}/keyscreens/blog-list.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Program: List
    label: 'Program: List',
    url: `${config.env}/keyscreens/program-finder.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Event: List
    label: 'Event: List',
    url: `${config.env}/keyscreens/event-list.html`,
    readySelector: '',
    delay: 0,
    selectors: '',
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
  {
    // Events 3 up
    label: 'Events 3up Feature',
    url: `${config.env}/keyscreens/pattern-objects.html`,
    readySelector: '.events3up',
    scrollToSelector: '.events3up',
    delay: 100,
    selectors: ['.events3up'],
    selectorExpansion: true,
    expect: 0,
    misMatchThreshold: 0.1,
    requireSameDimensions: true,
  },
];

module.exports = pathConfig;
