module.exports = {
  folder: {
    tasks: 'tasks',
    src: 'src',
    build: 'assets',
    temp: '.temp',
  },
  file: {
    mainHtml: 'index.html',
    mainJs: 'app.js',
    mainJsMin: 'app.min.js',
    vendorJs: 'vendor.js',
    vendorJsMin: 'vendor.min.js',
    vendorJsTemp: 'vendor.temp.js',
    mainScss: 'styles.scss',
    mainScssMin: 'styles.min.css',
    vendorScss: 'vendor.scss',
    vendorScssMin: 'vendor.min.css',
  },
  buildHtml: {
    templates: 'src/html/templates',
    dest: './assets',
  },
  task: {
    lintHtml: 'lint-html',
    lintJs: 'lint-js',
    buildHtml: 'build-html',
    buildJs: 'build-js',
    buildJsVendors: 'build-js-vendors',
    buildStyles: 'build-styles',
    buildStylesVendors: 'build-styles-vendors',
    imageMin: 'image-min',
    cleanBuild: 'clean-build',
    browserSync: 'browser-sync-server',
    watch: 'watch',
  },
  imageExtensions: 'jpg|jpeg|png|svg|gif|ico|tiff',
};
